[package]
name = "RLisp"
version = "0.1.0"
authors = ["RaphaelKreft <r.kreft@unibas.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "0.1.*"
rustyline = "8.0.0"
structopt = "0.3.13"